---
- hosts: tomcatServer
  vars:
  - warName: webapp.war
  - warRemotePath: /home/ubuntu/apache-tomcat-9.0.45/webapps
  - warLocalPath: /home/ubuntu/workspace/workspace/TestJob/webapp/target
  tasks:
  - name: Download WAR to server
    synchronize: src={{ warLocalPath }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }}

  - name: Unzip WAR file
    unarchive: src={{ warRemotePath }}/{{ warName }} dest=/home/ubuntu/apache-tomcat-9.0.45/webapps/ROOT copy=no mode=0755 owner=ec2-user group=ec2-user

  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent
