---
- hosts: tomcatServer
  vars:
  - warName: webapp.war
  - warRemotePath: /home/ec2-user/apache-tomcat-9.0.56/webapps
  - warLocalPath: /var/lib/jenkins/workspace/TestJob/webapp/target/webapp.war
  tasks:
  - name: Download WAR to server
    synchronize: src={{ warLocalPath }}/{{ warName }} dest={{ warRemotePath }}/{{ warName }}

  - name: Unzip WAR file
    unarchive: src={{ warRemotePath }}/{{ warName }} dest=/home/ec2-user/apache-tomcat-9.0.56/webapps/server copy=no mode=0755 owner=ec2-user group=ec2-user

  - name: Delete remote war file
    file: path={{ warRemotePath }}/{{ warName }} state=absent
